package org.mdolidon.hamster.CLI;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;


/**
 * Command-line parse results, generated by the JCommander library.
 * 
 */
public class CommandLine {

	@Parameter(names = { "init" }, description = "Create a new job")
	private boolean isInit;

	@Parameter(names = { "help", "--help", "-h" }, description = "...you already know")
	private boolean helpAsked;
	
	@Parameter(names = { "debug", "--debug"}, description = "Sets logging level to TRACE")
	private boolean debug;
	
	@Parameter(names = { "resume", "--resume"}, description = "Restarts from the memento file")
	private boolean resume;
	
	@Parameter(names = { "configure"}, description = "Request the help topic about configuration")
	private boolean configuration;
	

	public static CommandLine parse(String[] args) {
		CommandLine cl = new CommandLine();
		JCommander.newBuilder().addObject(cl).build().parse(args);
		return cl;
	}

	public boolean isInit() {
		return isInit;
	}

	public boolean isHelpAsked() {
		return helpAsked;
	}
	
	public boolean isConfigurationTopicAsked() {
		return configuration;
	}
	
	public boolean isDebug() {
		return debug;
	}
	
	public boolean isResume() {
		return resume;
	}

}
