package org.mdolidon.hamster.CLI;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;


/**
 * Command-line parse results, generated by the JCommander library.
 * 
 */
public class CommandLine {

	@Parameter(names = { "init" }, description = "Create a new job")
	private boolean isInit;

	@Parameter(names = { "help", "--help", "-h" }, description = "...you already know")
	private boolean helpAsked;
	
	@Parameter(names = { "debug", "--debug"}, description = "Sets logging level to TRACE")
	private boolean debug;
	
	@Parameter(names = { "resume", "--resume"}, description = "Restarts from the memento file")
	private boolean resume;
	
	@Parameter(names= {"retry", "--retry"}, description = "Retry downloads that failed on the latest job")
	private boolean retry;
	
	@Parameter(names= {"info","--info"}, description ="Information flag. Can be associated to other commands.")
	private boolean info;
	
	@Parameter(names= {"dont"}, description="Dont flat. Can be associated to other commands.")
	private boolean dont;
	
	@Parameter(names = { "configure"}, description = "Request the help topic about configuration")
	private boolean configuration;
	
	@Parameter(names = { "version", "--version", "about","--about"}, description = "Version number")
	private boolean version;
	

	public static CommandLine parse(String[] args) {
		CommandLine cl = new CommandLine();
		JCommander.newBuilder().addObject(cl).build().parse(args);
		return cl;
	}

	public boolean isInit() {
		return isInit;
	}

	public boolean isHelpAsked() {
		return helpAsked;
	}
	
	public boolean isConfigurationTopicAsked() {
		return configuration;
	}
	
	public boolean isDebug() {
		return debug;
	}
	
	public boolean isResume() {
		return resume;
	}
	
	public boolean isRetry() {
		return retry;
	}
	
	public boolean isInfoRequest() {
		return info;
	}
	
	public boolean isDontFlag() {
		return dont;
	}
	
	public boolean isVersionAsked() {
		return version;
	}

}
